services:
  - type: web
    name: selga
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: APP_BASE_URL
        value: https://selga.no
      - key: VIPPS_REDIRECT_URI
        value: https://selga.no/auth/vipps/callback
